apiVersion: v1
kind: Pod
metadata:
  name: stagiaire-copier-et-modifier-stackoverflow
  namespace: market
spec:
  hostPID: true
  containers:
    - name: une-application-web-container
      image: busybox
      command: ["sh", "-c", "sleep 1d"]
      securityContext:
        privileged: true
### Les configurations des services, ingress, etc., sont ignorées dans cette démonstration.
### Seul l’environnement de production peut être exposé au public.